APPLICATIONS = [
    {
        "program": "YC",
        "questions": [
            "Company name",
            "Describe what your company does in 50 characters or less",
            "Company url, if any",
            "If you have a demo, attach it below",
            "Please provide a link to the product, if relevant",
            "What is your company going to make? Please describe your product and what it does or will do",
            "Where do you live now, and where would the company be based after YC?",
            "Please record a one minute video introducing the founder(s).",
            "Who writes code, or does other technical work on your product? Was any of it done by a non-founder? Please explain.",
            "How long have the founders known one another and how did you meet? Have any of the founders not met in person?",
            "Are you looking for a cofounder?",
            "How far along are you?",
            "How long have each of you been working on this? How much of that has been full-time? Please explain.",
            "Are people using your product?",
            "How many active users or customers do you have? How many are paying? Who is paying you the most, and how much do they pay you?",
            "Do you have revenue?",
            "Where does your revenue come from? If your revenue comes from multiple sources (ex. multiple products, multiple companies or a mix of consulting and this product), please break down how much is coming from each source.",
            "Anything else you would like us to know regarding your revenue or growth rate?",
            "If you are applying with the same idea as a previous batch, did anything change? If you applied with a different idea,why did you pivot and what did you learn from the last idea?",
            "If you have already participated or committed to participate in an incubator, 'accelerator' or 'pre-accelerator' program, please tell us about it.",
            "Why did you pick this idea to work on? Do you have domain expertise in this area? How do you know people need what you're making?",
            "Who are your competitors? What do you understand about your business that they don't?",
            "How do or will you make money? How much could you make?",
            "How do users find your product? How did you get the users you have now? If you run paid ads, what is your cost of acquisition?",
            "If you track metrics around user engagement and retention, what are they?"
            "Where will most of your initial users be located?",
            "Have you formed ANY legal entity yet?",
            "How much money have you raised from investors in total in US Dollars?",
            "Are you currently fundraising?",
            "Please provide any relevant details about your current fundraise.",
            "If you have not formed the company yet, describe the planned equity ownership breakdown among the founders, employees and any other proposed stockholders. If there are multiple founders, be sure to give the proposed equity ownership of each founder and founder title (e.g. CEO).",
            "Please tell us in one or two sentences about the most impressive thing other than this startup that you have built or achieved.",
        ],
        "responses": [],
    },
    {
        "program": "MassChallenge US",
        "questions": [
            "Please describe what problem you are trying to solve?",
            "What is innovative about your solution, technology, business model etc?",
            "Define the 1 year and 5 year impact that you hope to accomplish including the benefit on society. What measures do you have - for example: Revenue & Profit, and CO2/Emissions removed or lives saved.",
            "How would you define your potential market and what is the total addressable market size?",
            "What traction have you made to date with market validation?",
            "What will be your messaging to users & customers and how do you plan to spread that message?",
            "Which channels will you likely reach your customers/users through?",
            "Which organizations compete with your current value offering and who might do so in the future?",
            "Which organizations and/or products complement your offering in the market? Do you know of and/or anticipate any value chain partners?",
            "What are your primary advantages relative to existing or potential competitors? Why will you win?",
            "What are the key drivers of business economics (price points, margins, etc)?",
            "What IP (Intellectual Property) exist for your business or in your industry?",
            "What regulatory requirements exist for your business or in your industry?",
            "Please share some background information on your team members and tell us what makes your team special.",
            "Please tell us about current or anticipated advisors and investors.",
        ],
    },
    {
        "program": "Google Accelerator",
        "questions": [
            "Email Address",
            "Preferred Contact Number",
            "What is your role?",
            "Company Name",
            "Legal Name of Company",
            "Website Link",
            "When was your startup founded?",
            "In what city is your startup headquartered?",
            "What is the mailing address of your legal entity?",
            "Describe your startup in one sentence",
            "What is your business model?",
            "What industry/vertical is most applicable to your startup?",
            "Please provide link(s) to your company page on Pitchbook/Crunchbase/Tracxn, if available",
            "How many C-level and/or founding team members are full-time?",
            "Please share the name of your founder(s) and a short bio for each person",
            "How long have they been working as a team?",
            "Please share e-mail addresses of your co-founders",
            "What roles are you looking to hire in the next 6 months?",
            "How many people does your company currently employ full-time?",
            "What is the problem that you are solving?",
            "What is your solution to this problem?",
            "Who are or might be your competitors?",
            "How is your solution different from your competitors?",
            "What are your major product milestones for the next 6 months?",
            "What are your primary and secondary target countries, if applicable?",
            "If applicable, what was your customer growth rate over the last 6 months?",
            "Provide 1-2 sentence description of your company (in English)",
            "What is your company Twitter handle? Please provide a url, if available",
            "What is your company LinkedIn handle? Please provide a url, if available",
            "What is your startup's current valuation in millions USD?",
            "Since founded, how much funding has your startup raised in millions USD?",
            "If you've raised funding who are your investors? Write N/A if not applicable",
            "What is your company's monthly recurring revenue (MRR)?",
            "Looking back at the last 6 months, what was the primary revenue source for the company?",
            "What is your startup's monthly burn rate?",
            "What is your forecasted revenue for the next 6 months?",
            "Please upload a pitch deck for your startup",
            "Which Google products are you using?",
            "Who would be a typical user/customer?",
            "Do you use machine learning today? If so, how?",
            "Please describe the main components in your system architecture",
            "What problem would you be looking to solve during the accelerator?",
            "If available, share a demo URL, video link, or screen recording of your product. Please write N/A if not available",
            "If available, share a link to your app on the Google Play Store",
            "If available, share a link to your app on the App Store",
            "Please provide a short, 1 sentence summary of app / product",
            "Why are you interested in joining this program? How can Google help?",
            "How did you hear about this program?",
            "If selected, are you interested in participating in possible interviews with local press outlets, as requested?",
            "Anything else you'd like to share?",
            "Please list links to any press coverage, awards or nominations and dates received given to your startup or founding team",
            "Please list any past accelerator or startup program participation",
            "Please upload a 2-minute video introducing your co-founders and elevator pitch",
            "Please share with us a high resolution photo(s) of the founder(s) and/or team from your startup",
            "Please share with us a high resolution logo",
        ],
    },
    {
        "program": "Norrsken Accelerator",
        "questions": [
            "What is the name of your company?",
            "Company URL",
            "Describe what your company does in <100 characters",
            "When did your company start operating?",
            "In which country do you primarily operate in?",
            "What is the problem you are trying to solve and who benefits from this problem being solved?",
            "How does your product address or solve this problem?",
            "What are some of the negative risks or consequences of your solution?",
            "What is your vision with the company?",
            "What are the main challenges you are currently facing?",
            "What challenges are you expecting to encounter when scaling your product?",
            "What challenges are you expecting to encounter when scaling your product?",
            "Who are the co-founders & what are their roles?",
            "Please add the LinkedIn profiles of all the co-founders in the following questions",
            "What makes you and your team the best in the world to build this solution",
            "How do you (the founding team) know each other?",
            "How many full-time employees do you currently have (excluding the co-founders)?",
            "How many of the co-founders are currently engaged full-time with your startup?",
            "Which tech category best applies to your company?",
            "What is the primary component of your business model?",
            "Please describe your target customer and where they will initially be located (geographically)?",
            "How do you define your addressable market? How big is it?",
            "Competitors! Everyone has them. Who are yours? How do you differ from them?",
            "How far have you come with your product?",
            "Where are you right now in terms of customers?",
            "When do you expect that your product will have users, and what are the barriers for launching now?",
            "What is your current MRR and growth rate?",
            "How do you make money?",
            "What milestones have you achieved since you began?",
            "What are you looking to achieve in the next 6 months?",
            "What milestones have you achieved since you last applied?",
            "What approval do you need and do you have it already? If not, when do you expect to have it by?",
            "Which Sustainable Development Goal does your solution contribute towards the most clearly?",
            "Please explain as clearly as possible how your product will have a positive impact?",
            "If your product is successful beyond your wildest dreams, what impact would this have on the world?",
            "If you have already participated (or committed to participate) in an incubator, 'accelerator' or "
            "'pre - accelerator' program, please tell us about it",
            "How much have you raised in total?",
            "Please list who has invested",
            "Please provide any relevant details about your current fundraise",
            "How much ownership do the co-founders have in the company?",
            "What is your current pre-money valuation?",
            "As it currently stands, how long is your runway?",
            "What is the primary reason you want to join the Norrsken Accelerator & what do you want to get out of it?",
            "What is your full name?",
            "What is your title?",
            "What email can we reach you on?",
            "Provide the email address of one of the other co-founders in the startup",
        ],
    },
    {
        "program": "Dantia",
        "questions": [
            "Startup name",
            "Website",
            "Is this your first startup? If no, what happened with your previous startups?",
            "Did you get any outside help to build this startup? Was any of the work done by a non-founder?",
            "How did the founders meet?",
            "Are you looking for more cofounders? If Yes, please specify why.",
            "What your company does in 100 characters or less.",
            "What is the problem you are trying to solve? Why are you passionate about it?",
            "How big is this problem?",
            "When and why did you decide to work on this idea?",
            "Who are your customers?",
            "How do you know people need what you're making?",
            "What is your product and how will it solve the problem?",
            "What is your progress till today? How far along are you?",
            "Are people using your product?",
            "How many active users or customers do you have?",
            "Are you charging your users? If not, why? If yes, how many are paying?",
            "Are you projecting more revenue in the next 6 months? If yes, why and how much?",
            "How do users find your product? How did you get the users you have now?",
            "What is your CAC and LTV?",
            "Do you track any metrics, what are they? Why did you decide to track these metrics?",
            "Do you have LOIs or partnerships?",
            "What is your GTM strategy?",
            # "Why are you passionate about solving this problem?",
            "Why does it matter to you as a person and as a team?",
            "Why are you the best team to work on this problem?",
            "Who are your competitors? How different are you from them?",
            "What are your major product milestones for the next 6 months?",
            "How will you make money? How much could you make?",
            "Where will most of your initial user base be located?",
            "What is your burn rate and current run rate?",
            "Are there barriers to entry in your market? License, permits",
            "Have you formed any legal entity yet?",
            "Do you have advisors/mentors? If yes, list their names and LinkedIn profiles. Do they own equity in any form?",
            "What is the equity breakdown for all founders?",
            "Do you have employees? Any ESOP?",
            "What will happen after 10 years if you have a massive success?",
        ],
    },
]
